action_map:
  0:
    type: move
    index: 0
    terastal: false
  1:
    type: move
    index: 1
    terastal: false
  2:
    type: move
    index: 2
    terastal: false
  3:
    type: move
    index: 3
    terastal: false
  4:
    type: move
    index: 0
    terastal: true
  5:
    type: move
    index: 1
    terastal: true
  6:
    type: move
    index: 2
    terastal: true
  7:
    type: move
    index: 3
    terastal: true
  8:
    type: switch
    index: 0
  9:
    type: switch
    index: 1
