rewards:
  knockout:
    weight: 1.0
    enabled: true
  turn_penalty:
    weight: 1.0
    enabled: true
  fail_immune:
    weight: 2.0
    enabled: true
    penalty: -0.3
  switch_penalty:
    weight: 1.0
    enabled: true
    penalty: -1.0
    threshold: 7
  pokemon_count:
    weight: 1.0
    enabled: true
