my_active:
  active_current_hp_frac:
    dtype: float
    battle_path: active.current_hp_fraction
    encoder: identity
    default: '1'
  active_move1_type:
    dtype: pkemontype
    battle_path: active_sorted_moves[0].type.name.lower()
    encoder: onehot
    default: '[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]'
  active_move1_base_power:
    dtype: int
    battle_path: active_sorted_moves[0].type.base_power
    encoder: linear_scale
    default: '0'
    range:
    - 0
    - 255
    scale_to:
    - 0
    - 1
opp_active:
  opp_active_current_hp_frac:
    dtype: float
    battle_path: battle.opponent_active_pokemon.current_hp_fraction
    encoder: identity
    default: '1'
my_bench1:
  my_bench1_current_hp_frac:
    dtype: float
    battle_path: bench1.current_hp_frac
    encoder: identity
    default: '1'
my_bench2:
  my_bench2_current_hp_frac:
    dtype: float
    battle_path: bench2.current_hp_frac
    encoder: nan
    default: '1'
opp_bench1:
  opp_bench1_current_hp_frac:
    dtype: float
    battle_path: opp_bench1.current_hp_fraction
    encoder: identity
    default: '1'
opp_bench2:
  opp_bench2_current_hp_frac:
    dtype: float
    battle_path: opp_bench2.current_hp_fraction
    encoder: identity
    default: '1'
field:
  weather:
    dtype: weather
    battle_path: AbstractBattle.weather[0]
    encoder: onehot
    default: '[1,0,0,0,0,0,0,0,0]'
meta:
  turn_count:
    dtype: int16
    battle_path: battle.turn
    encoder: identity
    default: '0'
  my_remaining_pokemon:
    dtype: int
    battle_path: my_alive_count
    encoder: identity
    default: '3'
  opp_remaining_pokemon:
    dtype: int
    battle_path: opp_alive_count
    encoder: identity
    default: '3'
