# Configuration for Pokemon Species Embedding Training
episodes: 100
lr: 0.0003
batch_size: 4096
buffer_capacity: 400000
gamma: 0.997
gae_lambda: 0.95
clip_range: 0.2
value_coef: 0.6
entropy_coef: 0.02
ppo_epochs: 4
algorithm: ppo
reward: composite
reward_config: config/reward.yaml

# Training configuration
parallel: 20
checkpoint_interval: 500
checkpoint_dir: "checkpoints"
tensorboard: true

# Team configuration
team: "random"  # Random teams to test species embedding
teams_dir: null

# Opponent configuration
opponent: max
opponent_mix: null

# Self-play win rate based opponent update
win_rate_threshold: 0.8
win_rate_window: 100

# Model management
load_model: null
save_model: null

# Pokemon Species Embedding Network Configuration
network:
  type: "embedding"  # New embedding network type
  hidden_size: 256
  use_2layer: true
  
  # Embedding-specific configuration
  embedding_config:
    embed_dim: 32  # Embedding dimension (must be >= 6 for base stats)
    vocab_size: 1026  # 0 (unknown) + 1025 (Pokemon species)
    freeze_base_stats: false  # Whether to freeze base stats dimensions during training
    
    # Species indices in state vector (automatically detected if not provided)
    # Indices 836-847: my_team[0-5].species_id + opp_team[0-5].species_id
    species_indices: [836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847]

# Sequence learning (disabled for basic embedding testing)
sequence_learning:
  enabled: false
  bptt_length: 0
  grad_clip_norm: 2.0