episodes: 10
lr: 0.003
parallel: 3
batch_size: 1024
buffer_capacity: 2048
algorithm: ppo
reward: composite
team: default
opponent: max
tensorboard: true

# Pokemon Showdown server configuration (single server for development)
pokemon_showdown:
  servers:
    - host: "localhost"
      port: 8000
      max_connections: 10  # Single server with lower capacity for development

network:
  type: basic
  hidden_size: 128
  use_2layer: true
exploration:
  epsilon_greedy:
    enabled: false
league_training:
  enabled: false